/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package birthdayDB;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;

/**
 *
 * @author gavin
 */
public class birthdayDB extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form birthdayDB
     */
    public birthdayDB() {
        initComponents();
        
        Object col[] = {"FirstName", "LastName", "YearMet", "Day", "Month", "Year", 
            "Address", "PhoneNumber", "FavouriteFood", "FavouriteSport", "FavouriteShow"};
        
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = birthdayDB.ConnectDB();
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
    
public static Connection ConnectDB() {
    try {
        Class.forName("org.sqlite.JDBC");
        Connection conn = DriverManager.getConnection("jdbc:sqlite:dataform.db");
        return conn;
    }
    catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, e);
        return null;
    }
}

public void updateTable() {
    conn = birthdayDB.ConnectDB();
    if (conn != null) {
        String sql = "Select FirstName, LastName, YearMet, Day, Month, Year, Address, "
                + "PhoneNumber, FavouriteFood, FavouriteSport, FavouriteShow from dataform";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Object[] columnData = new Object[11];
            
            while (rs.next()) {
                columnData[0] = rs.getString("FirstName");
                columnData[1] = rs.getString("LastName");
                columnData[2] = rs.getString("YearMet");
                columnData[3] = rs.getString("Day");
                columnData[4] = rs.getString("Month");
                columnData[5] = rs.getString("Year");
                columnData[6] = rs.getString("Address");
                columnData[7] = rs.getString("PhoneNumber");
                columnData[8] = rs.getString("FavouriteFood");
                columnData[9] = rs.getString("FavouriteSport");
                columnData[10] = rs.getString("FavouriteShow");
                model.addRow(columnData);
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtDay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtPhoneNumber = new javax.swing.JTextField();
        jtxtFavouriteFood = new javax.swing.JTextField();
        jtxtFavouriteSport = new javax.swing.JTextField();
        jtxtFavouriteShow = new javax.swing.JTextField();
        jtxtYearMet = new javax.swing.JTextField();
        cboMonth = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Year Met", "Day", "Month", "Year", "Address", "Phone Number", "Favourite Food", "Favourite Sport", "Favourite Show"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1420, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1440, 370));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 220, 40));

        jbtnAddNew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAddNew.setText("Add New");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 40));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 220, 40));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 220, 40));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1440, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("First Name");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtxtFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jtxtLastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLastNameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 260, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Day");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jtxtDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Month");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Year");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jtxtYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 260, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 730, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Phone Number");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Favourite Food");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Favourite Sport");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Favourite Show");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Year Met");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jtxtPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPhoneNumberActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 60, 260, -1));

        jtxtFavouriteFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtFavouriteFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, 260, -1));

        jtxtFavouriteSport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtFavouriteSport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, 260, -1));

        jtxtFavouriteShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jtxtFavouriteShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, 260, -1));

        jtxtYearMet.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtYearMet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtYearMetActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtYearMet, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 260, -1));

        cboMonth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month of Birth", "January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonthActionPerformed(evt);
            }
        });
        jPanel3.add(cboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 260, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1440, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed
        DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        
        String sql = "INSERT INTO dataform(FirstName, LastName, YearMet, Day, Month, Year, Address, "
                + "PhoneNumber, FavouriteFood, FavouriteSport, FavouriteShow)VALUES(?,?,?,?,?,?,?,?,?,?,?)";
        try {
            pst = conn.prepareStatement(sql);
            
            pst.setString(1, jtxtFirstName.getText());
            pst.setString(2, jtxtLastName.getText());
            pst.setString(3, jtxtYearMet.getText());
            pst.setString(4, jtxtDay.getText());
            pst.setString(5, (String) cboMonth.getSelectedItem());
            pst.setString(6, jtxtYear.getText());
            pst.setString(7, jtxtAddress.getText());
            pst.setString(8, jtxtPhoneNumber.getText());
            pst.setString(9, jtxtFavouriteFood.getText());
            pst.setString(10, jtxtFavouriteSport.getText());
            pst.setString(11, jtxtFavouriteShow.getText());
                
            pst.execute();
            JOptionPane.showMessageDialog(null, "Table Updated");
            rs.close();
            pst.close();
        }
        catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        updateTable();
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        try {
            jtxtFirstName.setText(null);
            jtxtLastName.setText(null);
            jtxtYearMet.setText(null);
            jtxtDay.setText(null);
            cboMonth.setSelectedIndex(0);
            jtxtYear.setText(null);
            jtxtAddress.setText(null);
            jtxtPhoneNumber.setText(null);
            jtxtFavouriteFood.setText(null);
            jtxtFavouriteSport.setText(null);
            jtxtFavouriteShow.setText(null);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtYearMetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtYearMetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtYearMetActionPerformed

    private void jtxtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPhoneNumberActionPerformed

    private void jtxtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLastNameActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Data Entry Form",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void cboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonthActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data to update ",
                        "Data Form", JOptionPane.OK_OPTION);
            }
            else {
                JOptionPane.showMessageDialog(null, "Select a row to update ",
                        "Data Form", JOptionPane.OK_OPTION);
            }
        }
        else {
            String sql = "UPDATE dataform SET FirstName = ?, LastName = ?, YearMet = ?, "
                    + "Day = ?, Month = ?, Year = ?, Address = ?, PhoneNumber = ?, FavouriteFood = ?, "
                    + "FavouriteSport = ?, FavouriteShow = ?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, jtxtFirstName.getText());
                pst.setString(2, jtxtLastName.getText());
                pst.setString(3, jtxtYearMet.getText());
                pst.setString(4, jtxtDay.getText());
                pst.setString(5, (String) cboMonth.getSelectedItem());
                pst.setString(6, jtxtYear.getText());
                pst.setString(7, jtxtAddress.getText());
                pst.setString(8, jtxtPhoneNumber.getText());
                pst.setString(9, jtxtFavouriteFood.getText());
                pst.setString(10, jtxtFavouriteSport.getText());
                pst.setString(11, jtxtFavouriteShow.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated");
            }
            catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            mod.setRowCount(0);
            updateTable();
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No data to delete ",
                        "Data Form", JOptionPane.OK_OPTION);
            }
            else {
                JOptionPane.showMessageDialog(null, "Select a row to delete ",
                        "Data Form", JOptionPane.OK_OPTION);
            }
        }
        else {
            String sql = "DELETE FROM dataform WHERE FirstName = ? AND LastName = ? AND YearMet = ? AND "
                    + "Day = ? AND Month = ? AND Year = ? AND Address = ? AND PhoneNumber = ? AND FavouriteFood = ? AND "
                    + "FavouriteSport = ? AND FavouriteShow = ?";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, jtxtFirstName.getText());
                pst.setString(2, jtxtLastName.getText());
                pst.setString(3, jtxtYearMet.getText());
                pst.setString(4, jtxtDay.getText());
                pst.setString(5, (String) cboMonth.getSelectedItem());
                pst.setString(6, jtxtYear.getText());
                pst.setString(7, jtxtAddress.getText());
                pst.setString(8, jtxtPhoneNumber.getText());
                pst.setString(9, jtxtFavouriteFood.getText());
                pst.setString(10, jtxtFavouriteSport.getText());
                pst.setString(11, jtxtFavouriteShow.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deleted");
            }
            catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            mod.setRowCount(0);
            updateTable();
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(birthdayDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(birthdayDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(birthdayDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(birthdayDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new birthdayDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtDay;
    private javax.swing.JTextField jtxtFavouriteFood;
    private javax.swing.JTextField jtxtFavouriteShow;
    private javax.swing.JTextField jtxtFavouriteSport;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtPhoneNumber;
    private javax.swing.JTextField jtxtYear;
    private javax.swing.JTextField jtxtYearMet;
    // End of variables declaration//GEN-END:variables
}
